---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: shivam
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "iiitb/calculator"
        source: pull
      register: docker_pull_result
      become: true

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Run Docker container
      shell: docker run -it -d --name calculator iiitb/calculator